sudo: required

language: java

services:
  - docker

jdk: oraclejdk8

script: ./gradlew test -x signArchives

after_success: ./gradlew kafka-connect-hive:fatJar -x test -x signArchives && ./int_test.sh
