jobs:
  build:
    working_directory: ~/code
    docker:
      - image: openjdk:8
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew test